name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: d9fd30af-92c8-4394-81dd-ed92100791f2
      with:
        args: container:login
    - name: set remote
      run: git remote set-url origin https://heroku:d9fd30af-92c8-4394-81dd-ed92100791f2@git.heroku.com/homefix-dev.git
    - name: push and deploy
      run: git push origin HEAD:master -f
