name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: login
      uses: nyakaz73/heroku-django-deploy@v0.68 
      with:
        heroku_app_name : homefix-dev
        heroku_api_key: d9fd30af-92c8-4394-81dd-ed92100791f2
        heroku_email_address: 'yz7726@nyu.edu'
        use_git: true
        git_branch: master
