name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: login
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_app_name : homefix-dev
        heroku_api_key: d9fd30af-92c8-4394-81dd-ed92100791f2
        heroku_email: 'yz7726@nyu.edu'
        branch: "develop"
